language: node_js
node_js:
- iojs
- '0.12'
- '0.11'
- '0.10'
sudo: false
script: npm test
after_script:
- cat ./coverage/lcov.info | ./node_modules/.bin/codeclimate-test-reporter
- cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage
env:
  global:
  - secure: Cr3bWTtiArQ+RaGEVp3IbQEcZ0UhoqpDgKKGmOSEnY3UMhf50X6olmoBzN6TMsPVr94RpBg9DAaAt/8ijFlLC+yRRs0/6TguUEfiMCllAlvfj1iiMVnZbUGjSmD1w9EjTaknoBfvSmTsK9U65gcJfDo6DSboFsQwXrO47CqLWuc=
  - secure: cRZspB2OmtfucwsGAmV5huc6i0vwnNXW2fnRH9lusPVFT39fipyV/TODRhJrCbH5k/amzGCWeZYHSeYj83AWb2+xZQ6HiQDaROxh3UwubjNuxAlbnIv8GXLiW/L6H8nQBl5mJramU2xXOxjCqyQFGPIsSyT+VOO06EzyLsvLYPo=
notifications:
  email: false
  pushover:
    api_key:
       secure: JeYVKPqbEU2vP8Q44l1CIuXag9n2hTv87kxe4GN5+NvSpcrEjMs4yt61KVXC5KX1MJaWq2m9PwCTwwI+IByQ1HF9TUDfi0voyrZqLJBgSWx1YdF30880BYFIKxuW24LmgesETmAbxUtEUbufVOXA8JY7bqJmyKAj2MOJ1uy++MI=
    users:
      -
        secure: hTnsF5nXSbIo+0LXc2qcpxtH+fyRcLpVqXMO1XtpbYkh47cDo1B121PAx4QtpMZSXcCFIM7NBa+1YZp2vql23kRL/hPPXtZ8JifirFGaTU1WWnsCZynnT8Dr9GSc2P4/y5kwxBUeYzv9N93Kn+moTFwdJ9r3bFC2nhpHDxI9kNA=
